server:
  port: "8080"
  environment: "development"
  
database:
  url: "postgres://user:password@localhost:5432/subscriptions?sslmode=disable"
  max_connections: 25
  max_idle_connections: 5

logging:
  level: "info"
  format: "json"  # json or text