services:
  postgres:
    image: postgres:15-alpine
    container_name: subscription_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d subscriptions"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: subscription_service
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/subscriptions?sslmode=disable
      PORT: 8080
    restart: always

volumes:
  postgres_data: